spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:lightcodedev.sit.kmutt.ac.th}:${DB_PORT:3306}/${DB_NAME:lightcode}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:lightcode}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: ${DB_USER:root}
    username: ${DB_USER:root}
#    password: ${DB_PASS:1234}
    password: ${DB_PASS:lc12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    path: /api/graphql
    graphiql:
      enabled: true
      path: /playground
  main:
    allow-circular-references: true
  #  data: data.sql
#  sql:
#    init:
#      mode=always:
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html
    syntax-highlight:
      theme: monokai
      activated: true
    try-it-out-enabled: true
    tags-sorter: alpha
    filter: true

webclient:
  base-url:
#    js-server: http://${NODEX:lightcodedev.sit.kmutt.ac.th}:8000
    js-server: http://${NODEX:localhost}:8000
# incase port 8080 is already in use
#server:
#  port: 5000


jwt:
  secret: "RapeepatKlamjeen-AritachMark-AmornpongDuangchawee___!(@#*!@(#*)+!@(*#AI@(!*#!W@"
  refreshExpirationDateInMs: 600000

logging:
  file:
    name: logs/${ENV_LOG:local}_lc_backend_log.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    com:
      senior:
        dreamteam: INFO