name: 'Build push back image manaul'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag name
      type:
        description: 'type of image is stable or dev'
        required: true
        default: 'dev'
        type: choice
        options:
          - stable
          - dev

jobs:
  build-back-image:
    runs-on: ubuntu-latest
    steps:
    - name: Use Build and Push Docker Image action
      uses: SIT-LightCode/LC-Deployment/actions/build-push-back@main
      with:
        image: "back-end"
        tags: ${{ inputs.tag }}
        type: ${{ inputs.type }}
        ghcr_pat: ${{ secrets.GHCR_PAT }}
